### ISSUE TITLE
Default OS X scrollbars appear

### ISSUE THREAD

**Issue by cviebrock** [Charuru/lionbars#13]
In order to hide the default OS X scrollbars when using lionbars, I believe you need to add this to the stylesheet:

``` css
.lb-wrap::-webkit-scrollbar {
  visibility: hidden;
}
```
